### ISSUE TITLE
 action invoke on timed out/demoted activation response throws exception

### ISSUE THREAD

**Issue by rabbah** [adobe/aio-cli-plugin-runtime#101]
**Describe the bug**
If you executing a result only (`action invoke --result`) action and it exceeds the wait time allowed by the backend controller, the requests is demoted to an asynchronous request (API response code is 202) and the result is `{ activationId }`.

```
> ... action invoke name -r --verbose
  aio-cli-plugin-runtime TypeError: Cannot read property 'result' of undefined
  aio-cli-plugin-runtime     at invoke.then.result (/.../node_modules/@adobe/aio-cli-plugin-runtime/node_modules/openwhisk/lib/actions.js:48:67)
  aio-cli-plugin-runtime     at process._tickCallback (internal/process/next_tick.js:68:7) +1m
 ›   Error: failed to invoke the action: Cannot read property 'result' of undefined
 ›     specify --verbose flag for more information
```

The deficiency comes from the npm openwhisk library itself https://github.com/apache/openwhisk-client-js/issues/198.

**To Reproduce**
1. Create an action with a time limit greater than 60s
2. Invoke the action with `--result`
3. See error

**Expected behavior**
The CLI should detect the demotion and output a message:
```
Your request took longer than expected. Use activation id ... to retrieve the results later.
```

I have a patch for this bug which works around the `npm openwhisk` issue while waiting for a proper fix from the Apache project. I am happy to open a PR now or wait (which removes hacking around the openwhisk client).

**Comment by meryllblanchet** [comment]
Hi @rabbah and thanks for this new contribution!
Do you have any idea of the ETA for the fix at openwhisk level?

Cheers,

Meryll

**Comment by rabbah** [comment]
Likely about a week until a new release is cut at best.

**Comment by meryllblanchet** [comment]
Thanks for the prompt answer, then I'd suggest waiting for this one!

**Comment by rabbah** [comment]
npm OpenWhisk 3.21.1 is out with necessary patches. PR is ready for review.

**Comment by rabbah** [comment]
PR was merged this can be closed.
