### ISSUE TITLE
aio rt:activation:list does NOT work in Windows 10

### ISSUE THREAD

**Issue by visaq** [adobe/aio-cli-plugin-runtime#102]
After deploying app into IO, I ran "aio app run" in command prompt and then using the url under web-src/src/config.json, I invoked my app. Then I entered "aio rt:activation:list" in Terminal tab of VS code and I got the below error. I got the same error when I repeated these same steps with "aio app run --local". However, "wsk activation list" gave me the list of activation ids.
"aio rt:activation:list
aio : File C:\Users\mallicha\AppData\Roaming\npm\aio.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at      
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ aio rt:activation:list
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess"

OS: Windows 10 Enterprise
Browse: Google Chrome - Version 79.0.3945.130 (Official Build) (64-bit)
aio --version --> @adobe/aio-cli/3.0.0 win32-x64 node-v12.13.1

![Issue-ActicationList](https://user-images.githubusercontent.com/36865208/73579457-1f332100-4448-11ea-8c69-e60d7cd4d17a.jpg)

**Comment by DrewML** [comment]
Hey @visaq,

Unfortunately this is a recent behavior change in `npm` which will cause this problem for any globally installed packages:

https://github.com/npm/cli/issues/470

Some work-arounds are offered in that thread

**Comment by meryllblanchet** [comment]
Closing the issue as this related to [npm/cli#470](https://github.com/npm/cli/issues/470)
