### ISSUE TITLE
apihost name does not tolerate trailing slash

### ISSUE THREAD

**Issue by rabbah** [adobe/aio-cli-plugin-runtime#118]
**Describe the bug**
Similar to the issue reported here apache/openwhisk-cli#481, a trailing `/` on the API host also causes a failure in aio.

**To Reproduce**

```
> ./bin/run runtime:action:list --apihost https://example.com/
 ›   Error: failed to list the actions: 404 Not Found
 ›     specify --verbose flag for more information
```

With the --verbose setting:
```
  aio-cli-plugin-runtime OpenWhiskError: GET https://example.com//api/v1/namespaces/_/actions Returned HTTP 404 (Not Found) --> "Response Missing Error Message."
```

**Expected behavior**
A trailing slash should be ignored.

**Comment by Himavanth** [comment]
Works now. Must have got fixed meanwhile. 
Closing this. Please feel free to reopen if it doesn't work for you.
