### ISSUE TITLE
code file links on README.md are broken (/blob/v1.4.0/ not found)

### ISSUE THREAD

**Issue by bhageena** [adobe/aio-cli-plugin-runtime#126]
all code file links point to blob **/blob/v1.4.0/**, and it is missing 
i.e. https://github.com/adobe/aio-cli-plugin-runtime/blob/v1.4.0/src/commands/runtime/trigger/update.js
![Screenshot from 2020-02-18 12-49-21](https://user-images.githubusercontent.com/14236753/74712777-22524d80-524d-11ea-98fe-365fc0fbdfdb.png)

**Comment by shazron** [comment]
Partially because of this: https://github.com/oclif/dev-cli/issues/123 (which has a workaround)

________________________________
