### ISSUE TITLE
[activation] allow filtering of activations

### ISSUE THREAD

**Issue by honstar** [adobe/aio-cli-plugin-runtime#136]
**Is your feature request related to a problem? Please describe.**
Via `aio:rt:activation:ls`, it is currently not possible to filter the list of activations. While it is possible to specify dates in milliseconds to narrow the list of returned activations, it is not really possible to find failed activations for troubleshooting purposes easily.

**Describe the solution you'd like**
How about adding an additional filter option that additionally allows for filtering the result set by available columns, i.e. `status`? That would allow for finding recent failed activations easily.

**Comment by rajarju** [comment]
Additional filtering is not possible from cli as the runtime api for `activations` does not support them. A work around could be to increase the `limit` and grep the result
