### ISSUE TITLE
ACNA-256 - Crashes if non existing WSK_CONFIG_FILE while setting WHISK_* vars

### ISSUE THREAD

**Issue by moritzraho** [adobe/aio-cli-plugin-runtime#14]
**Describe the bug**
I want to deploy my resources based solely on environment vars and make sure vars in my `.wskprops` file are not parsed. 

In wsk I can set the `WSK_CONFIG_FILE` to a non existing file and set WHISK_* env vars to define my namespace, auth and apihost.

In `aio runtime` if `WSK_CONFIG_FILE` is not existing an error is raised

Also `aio runtime list` and `aio runtime deploy` do not raise the same error

**To Reproduce**

In wsk I can do: 
`WSK_CONFIG_FILE=doesnotexist WHISK_NAMESPACE=<ns> WHISK_AUTH=<auth> WHISK_APIHOST=<apihost> wsk list`

`aio runtime list`: 
```
$ WSK_CONFIG_FILE=doesnotexist WHISK_NAMESPACE=<ns> WHISK_AUTH=<auth> WHISK_APIHOST=<apihost> aio runtime list
›   Error: failed to get the data for a namespace: {}
```
`aio runtime deploy`: 
```
$ WSK_CONFIG_FILE=doesnotexist WHISK_NAMESPACE=<ns> WHISK_AUTH=<auth> WHISK_APIHOST=<apihost> aio runtime deploy
›   Error: Failed to deploy: OpenWhisk config file 'doesnotexist' does not exist.
```

A simple workaround is to `touch doesnotexist` before and then it works just fine.

**Expected behavior**
No error or uniform error message

**Desktop (please complete the following information):**
`@adobe/aio-cli/1.4.1 darwin-x64 node-v10.15.3`

**Comment by purplecabbage** [comment]
I just tested against master and this appears to function identically to `wsk list` where WSK_CONFIG_FILE is only referenced if one of the required values is missing.
