### ISSUE TITLE
Feature request - Support shellscripts as main function

### ISSUE THREAD

**Issue by tmathern** [adobe/aio-cli-plugin-runtime#141]
Follow up of https://github.com/adobe/aio-cli/issues/130.

This is a feature request to handle the case when the function the manifest points to is a shellscript.

Example of part of such a manifest:

    actions:
      action_name:
        >>>>>**function: 'worker.sh'**
        runtime: 'nodejs:10'
        annotations:
          final: true

Currently, when trying to build and deploy, this fails with a webpack error: `./worker.sh 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/bin/bash
|`

Here is how I functionally envision the shellscript worker support:
- `function` in `manifest.yml` can point to a worker.sh
- the worker.sh gets package into the action package (no webpack needed for the sheelscript, so maybe just ignore it?)
- "neighboor" javascript files would also be added in the package (that's where we would need webpack, actually). This is needed because Nui auto-generates code (javascript) for shellscript workers before packaging. I plan to do that dynamic code generation in a pre-build aio hook. So, that generated code should be also packaged with the shellscript and be in the action (the entrypoint would be the dynamically generated index.js - maybe you will need to add a different `kind` for shellscripts worker? Or an `include`?).

I tried packaging a whole folder, but it didn't work either.

**Comment by fmeschbe** [comment]
We are build the manifest to deploy JavaScript actions in a _nodejs:10_ kind container. The only guarantee that we have there is a NodeJS environment. Including and calling shell scripts is risky and adds a deployment dependency which is not properly reflected with the _nodejs:10_ kind name.

Can you reimplement your shell script in Java Script and just deploy it as a regular JavaScript function, action, or module ?

As such, this ask cannot be fulfilled and is to be rejected.
