### ISSUE TITLE
aio runtime action get -r does return a different web action url than what aio app deploy prints

### ISSUE THREAD

**Issue by alexkli** [adobe/aio-cli-plugin-runtime#142]
`aio runtime action get -r`  returns:

```
https://adobeioruntime.net/api/v1/web/my-namespace/example-custom-worker-1.0.0/worker
```

but `aio app deploy` logged this “nicer” URL:

```
https://my-namespace.adobeioruntime.net/api/v1/web/example-custom-worker-1.0.0/worker
```

Would be good to stay consistent with one format everywhere, and possibly the "nicer" one.

**Comment by meryllblanchet** [comment]
Thanks for raising this up @alexkli !

The latter URL should be the one also printed out by `aio runtime action get -r`.

**Comment by meryllblanchet** [comment]
I realized meanwhile that we already had an issue opened for this bug.
I'll close the issue, you can follow-up there: https://github.com/adobe/aio-cli-plugin-runtime/issues/133
