### ISSUE TITLE
Support for storing activations for blocking calls

### ISSUE THREAD

**Issue by mcorlan** [adobe/aio-cli-plugin-runtime#146]
**Problem:** 

I/O Runtime doesn't store the activation record for successful blocking invocations. A developer testing code will need to add this header to each request if he wants to force the creation of the activation record: "X-OW-EXTRA-LOGGING: on".

**Solution:**

aio CLI could automatically add this header when used to invoke an action. I/O Runtime will honor the request if applicable or just discard it (no error thrown).

**Comment by rabbah** [comment]
Have you tried this feature against an active deployment? I am seeing failures against standalone openwhisk related to authentication. I believe that when a header is specified, `npm openwhisk` is not adding the basic auth header and all invokes fail.

```
 WSK_CONFIG_FILE=~/.local-wskprops ./bin/run runtime:action:invoke user/login
 ›   Error: failed to invoke the action: the resource requires authentication, which was not supplied with the request (401 Unauthorized)
 ›     specify --verbose flag for more information
```

running with DEBUG=* shows:
```
  { accept: 'application/json',
     'user-agent': 'Needle/2.4.1 (Node.js v10.16.3; darwin x64)',
     'x-ow-extra-logging': 'on',
     'content-length': 2,
     'content-type': 'application/json; charset=utf-8',
     host: 'localhost:3233' } } +0ms
```
