### ISSUE TITLE
Move createKeyValueObjectFromFlag to some other module

### ISSUE THREAD

**Issue by justinedelson** [adobe/aio-cli-plugin-runtime#147]
**Is your feature request related to a problem? Please describe.**

In https://github.com/adobe/aio-cli-plugin-cloudmanager, I need the same flag parsing logic for name-value pairs as is present in this plugin. To avoid copy/paste, that plugin depends upon this one. This seems like a bit of overkill and I'm thinking it might make sense to move that function into some common module. I don't have a good suggestion -- opening this issue to have a conversation about what might be a good place (or if this is a terrible idea).

**Describe the solution you'd like**

To be able to use `createKeyValueObjectFromFlag` without pulling in the full dependency chain from this plugin.

**Describe alternatives you've considered**

* What I do now :)
* Copy/paste this function

**Comment by purplecabbage** [comment]
Personally, I favor copy/paste in this case. 
If you plan on using this function across multiple libraries we could look at turning it into a standalone module.
