### ISSUE TITLE
chalk missing from package.json

### ISSUE THREAD

**Issue by rabbah** [adobe/aio-cli-plugin-runtime#151]
**Describe the bug**
A search on the aio repo shows there are a couple of references to `npm chalk`: https://github.com/adobe/aio-cli-plugin-runtime/search?q=chalk&unscoped_q=chalk

It was introduced in adobe/aio-cli-plugin-runtime@d22673f but is not declared in package.json. This can cause oclif clashes which is not compatible with later chalk versions.

**Expected behavior**
Add chalk 2.4.2 as a dependency to package.json.

**Comment by shazron** [comment]
This should be a test failure for the linter. Suggest using the `no-extraneous-require` rule: https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-extraneous-require.md

**Comment by shazron** [comment]
interestingly the rule caught `debug` being extraneous, but not `chalk`🤔

**Comment by shazron** [comment]
`no-missing-require` appears to be another rule to use, but it's having false positives for relative-pathed requires (probably a configuration issue).

**Comment by shazron** [comment]
Added this in `.eslintrc`:
```
    "rules": {
        "node/no-extraneous-require": ["error", {
            "allowModules": [],
            "resolvePaths": [],
            "tryExtensions": [".js"]
        }],
        "node/no-missing-require": ["error", {
            "allowModules": [],
            "resolvePaths": [],
            "tryExtensions": [".js"]
        }]
    }
```

Got these lint errors:
```
/Users/shazron/Documents/git/adobe/aio-cli-plugin-runtime/src/RuntimeBaseCommand.js
  16:29  error  "debug" is extraneous  node/no-extraneous-require

/Users/shazron/Documents/git/adobe/aio-cli-plugin-runtime/src/commands/runtime/activation/logs.js
  16:23  error  "chalk" is extraneous  node/no-extraneous-require

/Users/shazron/Documents/git/adobe/aio-cli-plugin-runtime/src/commands/runtime/property/get.js
  17:23  error  "debug" is extraneous  node/no-extraneous-require

/Users/shazron/Documents/git/adobe/aio-cli-plugin-runtime/src/runtime-helpers.js
  15:23  error  "debug" is extraneous  node/no-extraneous-require

/Users/shazron/Documents/git/adobe/aio-cli-plugin-runtime/test/RuntimeBaseCommand.test.js
  181:29  error  "debug" is extraneous  node/no-extraneous-require
  192:29  error  "debug" is extraneous  node/no-extraneous-require
  203:29  error  "debug" is extraneous  node/no-extraneous-require

/Users/shazron/Documents/git/adobe/aio-cli-plugin-runtime/e2e/e2e.js
  12:23  error  "execa" is extraneous  node/no-extraneous-require
  13:23  error  "chalk" is extraneous  node/no-extraneous-require
```

`debug` and `chalk` are need to be prod deps (thus dev as well), while `execa` is just a dev dep.

**Comment by shazron** [comment]
sent PR #152
