### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by ackoch** [adobe/aio-cli-plugin-runtime#226]
**Describe the bug**

Documentation says to install you'd have to call: 

aio plugins:install -g @adobe/aio-cli-plugin-runtime

but I think the "-g" is wrong (it yields an error and it works perfectly without)

**Comment by meryllblanchet** [comment]
Thanks for reporting the doc issue @ackoch !
Indeed, `-g` is not needed.

**Comment by dm-devtech** [comment]
Hi,
Please could I work on this issue?

**Comment by meryllblanchet** [comment]
PRs are welcome, even in the docs!

**Comment by purplecabbage** [comment]
Thanks @dm-devtech !
