### ISSUE TITLE
passing parameters with triggers is not the same as action (but should be)

### ISSUE THREAD

**Issue by rabbah** [adobe/aio-cli-plugin-runtime#230]
**Describe the bug**

Create a trigger, and connect it to an echo action, then fire the trigger:
```bash
./bin/run rt:trigger:fire mytrigger --param name test
```

The echo action receives:
```json
{
  "parameters": [
    {
      "key": "name",
      "value": "test"
    }
  ]
}
```

Retry with the `wsk` CLI and you get `{ "name": "test" }`

**To Reproduce**
1. Create trigger `mytrigger`, an `echo` action and a rule connecting the two
2. Activate the trigger as show above
3. Inspect the activation result for the `echo` action

**Expected behavior**
The parameters are sent as a JSON dictionary `{"name":"test"}` matching the `wsk` CLI.

Here is a potential patch to correct the issue https://github.com/adobe/aio-cli-plugin-runtime/compare/master...rabbah:trigger?expand=1.

**Comment by meryllblanchet** [comment]
Thanks for raising the issue, @rabbah ! 
Let us know if you have a PR handy, it will be welcome of course.
