### ISSUE TITLE
ACNA-324 - Support package binding through deploy command

### ISSUE THREAD

**Issue by Himavanth** [adobe/aio-cli-plugin-runtime#24]
**Is your feature request related to a problem? Please describe.**
Support package binding through deploy command

**Describe the solution you'd like**
manifest.yml should have the following structure for a package binding
packages:
  adobe-oauth:
    dependencies:
      # binding to shared oauth package
      myauthp-shared:
        location: /adobeio/oauth

**Comment by shazron** [comment]
ACNA-336 is a dupe of ACNA-324.
