### ISSUE TITLE
`aio runtime:list` should be documented

### ISSUE THREAD

**Issue by MichaelGoberling** [adobe/aio-cli-plugin-runtime#267]
**Describe the bug**
The `aio runtime:list` command is not present when running `aio runtime --help`. It is also not documented as part of the `README.md` of this repo. 

**To Reproduce**
1. Run `aio runtime --help`
2. Notice that `aio runtime:list` is not listed under `topics` or `commands`. 

**Expected behavior**
`aio runtime:list` should show up under `topics` or `commands`, it should also be documented as part of the `README.md` of this repo. 

**Screenshots**
<img width="630" alt="image" src="https://user-images.githubusercontent.com/28722775/172870698-d1ee0279-4f49-45ee-a770-edfe7784eb4e.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.1 (21C52)

**Comment by shazron** [comment]
`aio runtime list` is actually an alias for `aio runtime:namespace:get`.

See `aio runtime list --help`:
```
❯ aio runtime list --help
Get triggers, actions, and rules in the registry for namespace

USAGE
  $ aio runtime:namespace:get

OPTIONS
  -i, --insecure           bypass certificate check
  -n, --name               sort results by name
  -u, --auth=auth          whisk auth
  -v, --verbose            Verbose output
  --apihost=apihost        whisk API host
  --apiversion=apiversion  whisk API version
  --cert=cert              client cert
  --debug=debug            Debug level output
  --help                   Show help
  --json                   output raw json
  --key=key                client key
  --name-sort              sort results by name
  --version                Show version

ALIASES
  $ aio rt:get
  $ aio runtime:list
  $ aio rt:list
  $ aio runtime:ls
  $ aio rt:ls
```

Only actual commands (and not aliases) are listed in `aio runtime --help`
