### ISSUE TITLE
aio runtime action get --url for full action id return wrong url

### ISSUE THREAD

**Issue by OmarEltobgy** [adobe/aio-cli-plugin-runtime#94]
**Describe the bug**
For a web action, getting the url for it using the command `aio runtime action get --url <action_id>` returns a wrong url

**To Reproduce**
1. Deploy a web action (resource) in a package (package) to a runtime namespace (namespace)
2. List all action `aio rt:ls` and get the action id which will be something simiar to `/namespace/package/resource`
3. Run `aio runtime action get --url <action_id>`, you will get a "wrong" url `https://adobeioruntime.net/api/v1/web/namespace//namespace/package/resource`

**Expected behavior**
The url should be `https://adobeioruntime.net/api/v1/web/namespace/package/resource`. You can get the correct url if you send action_id as `package/resource` only NOT `/namespace/package/resource`

Note that I get a correct URL if I use wsk CLI `wsk action get --url <action_id>` if action_id is in both formats. 

**Suggested solution**
The result of `wsk action get --url <action_id>` should be returned instead of manually creating the url in this [line](https://github.com/adobe/aio-cli-plugin-runtime/blob/119ca32353921aa56963a56cbbedcfe8b597e72e/src/commands/runtime/action/get.js#L52) `

OR In this [line](https://github.com/adobe/aio-cli-plugin-runtime/blob/119ca32353921aa56963a56cbbedcfe8b597e72e/src/commands/runtime/action/get.js#L52), `${name}` shouldn't be used as it is the value of the input action name and this input value can be more than just the name including the package and namespace. And instead the action name value in the result should be used `result.name`

**Comment by rabbah** [comment]
I opened a PR for this.
